### ISSUE TITLE
글 등록시에 쿼리문을 3번쓰게 되는데, 성능상 개선할 방법이 있을까요?

### ISSUE THREAD

**Issue by siyoon210** [MisunJoo/Fantastic-Four-Board#3]
현재 글 등록시
1) Article 테이블의 글 등록
2) 등록한 글 아이디 받아오기
3) 글 아이디로 content테이블의 등록하기

총 3번의 쿼리가 진행되게 됩니다. 성능상으로 안 좋을 것같은데, 개선 방법이 없을까요??

**Comment by dpudpu** [comment]
:smile:
